//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WayvSL2ASPX.DirectoryServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectorySuscriptionsSoap", Namespace="http://wayv.tv/")]
    public partial class DirectorySuscriptions : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListWebChannelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewShowIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewVersionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSessionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitShowOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DirectorySuscriptions() {
            this.Url = global::WayvSL2ASPX.Properties.Settings.Default.WayvSL2ASPX_DirectoryServer_DirectorySuscriptions;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListWebChannelsCompletedEventHandler ListWebChannelsCompleted;
        
        /// <remarks/>
        public event GetNewShowIDCompletedEventHandler GetNewShowIDCompleted;
        
        /// <remarks/>
        public event GetNewVersionIDCompletedEventHandler GetNewVersionIDCompleted;
        
        /// <remarks/>
        public event GetSessionIDCompletedEventHandler GetSessionIDCompleted;
        
        /// <remarks/>
        public event SubmitShowCompletedEventHandler SubmitShowCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wayv.tv/ListWebChannels", RequestNamespace="http://wayv.tv/", ResponseNamespace="http://wayv.tv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebChannelInfo[] ListWebChannels() {
            object[] results = this.Invoke("ListWebChannels", new object[0]);
            return ((WebChannelInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListWebChannelsAsync() {
            this.ListWebChannelsAsync(null);
        }
        
        /// <remarks/>
        public void ListWebChannelsAsync(object userState) {
            if ((this.ListWebChannelsOperationCompleted == null)) {
                this.ListWebChannelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListWebChannelsOperationCompleted);
            }
            this.InvokeAsync("ListWebChannels", new object[0], this.ListWebChannelsOperationCompleted, userState);
        }
        
        private void OnListWebChannelsOperationCompleted(object arg) {
            if ((this.ListWebChannelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListWebChannelsCompleted(this, new ListWebChannelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wayv.tv/GetNewShowID", RequestNamespace="http://wayv.tv/", ResponseNamespace="http://wayv.tv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNewShowID() {
            object[] results = this.Invoke("GetNewShowID", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewShowIDAsync() {
            this.GetNewShowIDAsync(null);
        }
        
        /// <remarks/>
        public void GetNewShowIDAsync(object userState) {
            if ((this.GetNewShowIDOperationCompleted == null)) {
                this.GetNewShowIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewShowIDOperationCompleted);
            }
            this.InvokeAsync("GetNewShowID", new object[0], this.GetNewShowIDOperationCompleted, userState);
        }
        
        private void OnGetNewShowIDOperationCompleted(object arg) {
            if ((this.GetNewShowIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewShowIDCompleted(this, new GetNewShowIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wayv.tv/GetNewVersionID", RequestNamespace="http://wayv.tv/", ResponseNamespace="http://wayv.tv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNewVersionID(int pShowId) {
            object[] results = this.Invoke("GetNewVersionID", new object[] {
                        pShowId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewVersionIDAsync(int pShowId) {
            this.GetNewVersionIDAsync(pShowId, null);
        }
        
        /// <remarks/>
        public void GetNewVersionIDAsync(int pShowId, object userState) {
            if ((this.GetNewVersionIDOperationCompleted == null)) {
                this.GetNewVersionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewVersionIDOperationCompleted);
            }
            this.InvokeAsync("GetNewVersionID", new object[] {
                        pShowId}, this.GetNewVersionIDOperationCompleted, userState);
        }
        
        private void OnGetNewVersionIDOperationCompleted(object arg) {
            if ((this.GetNewVersionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewVersionIDCompleted(this, new GetNewVersionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wayv.tv/GetSessionID", RequestNamespace="http://wayv.tv/", ResponseNamespace="http://wayv.tv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSessionID() {
            object[] results = this.Invoke("GetSessionID", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSessionIDAsync() {
            this.GetSessionIDAsync(null);
        }
        
        /// <remarks/>
        public void GetSessionIDAsync(object userState) {
            if ((this.GetSessionIDOperationCompleted == null)) {
                this.GetSessionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSessionIDOperationCompleted);
            }
            this.InvokeAsync("GetSessionID", new object[0], this.GetSessionIDOperationCompleted, userState);
        }
        
        private void OnGetSessionIDOperationCompleted(object arg) {
            if ((this.GetSessionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSessionIDCompleted(this, new GetSessionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wayv.tv/SubmitShow", RequestNamespace="http://wayv.tv/", ResponseNamespace="http://wayv.tv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubmitShow(WebShowMetadata pMetadata, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] pZipPackage) {
            object[] results = this.Invoke("SubmitShow", new object[] {
                        pMetadata,
                        pZipPackage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitShowAsync(WebShowMetadata pMetadata, byte[] pZipPackage) {
            this.SubmitShowAsync(pMetadata, pZipPackage, null);
        }
        
        /// <remarks/>
        public void SubmitShowAsync(WebShowMetadata pMetadata, byte[] pZipPackage, object userState) {
            if ((this.SubmitShowOperationCompleted == null)) {
                this.SubmitShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitShowOperationCompleted);
            }
            this.InvokeAsync("SubmitShow", new object[] {
                        pMetadata,
                        pZipPackage}, this.SubmitShowOperationCompleted, userState);
        }
        
        private void OnSubmitShowOperationCompleted(object arg) {
            if ((this.SubmitShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitShowCompleted(this, new SubmitShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wayv.tv/")]
    public partial class WebChannelInfo {
        
        private int channelIdField;
        
        private string channelNameField;
        
        private string channelDescriptionField;
        
        private byte[] channelImageField;
        
        private byte[] channelLogoField;
        
        /// <remarks/>
        public int ChannelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelName {
            get {
                return this.channelNameField;
            }
            set {
                this.channelNameField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelDescription {
            get {
                return this.channelDescriptionField;
            }
            set {
                this.channelDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ChannelImage {
            get {
                return this.channelImageField;
            }
            set {
                this.channelImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ChannelLogo {
            get {
                return this.channelLogoField;
            }
            set {
                this.channelLogoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wayv.tv/")]
    public partial class WebShowMetadata {
        
        private int showIdField;
        
        private int versionField;
        
        private string showTitleField;
        
        private string descriptionField;
        
        private int channelIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ShowId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowTitle {
            get {
                return this.showTitleField;
            }
            set {
                this.showTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ChannelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ListWebChannelsCompletedEventHandler(object sender, ListWebChannelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListWebChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListWebChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebChannelInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebChannelInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetNewShowIDCompletedEventHandler(object sender, GetNewShowIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewShowIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewShowIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetNewVersionIDCompletedEventHandler(object sender, GetNewVersionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewVersionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewVersionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetSessionIDCompletedEventHandler(object sender, GetSessionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSessionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSessionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SubmitShowCompletedEventHandler(object sender, SubmitShowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591