//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerAlpha.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProducerAlpha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string AboutCommand {
            get {
                return ResourceManager.GetString("AboutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New Conversational Poll.
        /// </summary>
        internal static string AddNewConversationalPoll {
            get {
                return ResourceManager.GetString("AddNewConversationalPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New PageFrame.
        /// </summary>
        internal static string AddNewPageFrame {
            get {
                return ResourceManager.GetString("AddNewPageFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New Pageshot.
        /// </summary>
        internal static string AddNewPageShot {
            get {
                return ResourceManager.GetString("AddNewPageShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New VideoFrame.
        /// </summary>
        internal static string AddNewVideoFrame {
            get {
                return ResourceManager.GetString("AddNewVideoFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New Webslide.
        /// </summary>
        internal static string AddNewWebSlide {
            get {
                return ResourceManager.GetString("AddNewWebSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot Create Project.
        /// </summary>
        internal static string AnotherProjectInFolder {
            get {
                return ResourceManager.GetString("AnotherProjectInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Another project exists in this folder.
        /// </summary>
        internal static string AnotherProjectInFolderMessage {
            get {
                return ResourceManager.GetString("AnotherProjectInFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Cancelled.
        /// </summary>
        internal static string ChannelLogoTooLarge {
            get {
                return ResourceManager.GetString("ChannelLogoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image you are trying to import is too large for a Channel Logo.
        /// </summary>
        internal static string ChannelLogoTooLargeMessage {
            get {
                return ResourceManager.GetString("ChannelLogoTooLargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Cancelled.
        /// </summary>
        internal static string ChannelLogoTooSmall {
            get {
                return ResourceManager.GetString("ChannelLogoTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image you are trying to import is too small for a Channel Logo.
        /// </summary>
        internal static string ChannelLogoTooSmallMessage {
            get {
                return ResourceManager.GetString("ChannelLogoTooSmallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear All Console Contents.
        /// </summary>
        internal static string ClearConsoleCommand {
            get {
                return ResourceManager.GetString("ClearConsoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversational Poll.
        /// </summary>
        internal static string ConversationalPoll {
            get {
                return ResourceManager.GetString("ConversationalPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        internal static string CreateXamlLink {
            get {
                return ResourceManager.GetString("CreateXamlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to create a Link to the original Xaml File?.
        /// </summary>
        internal static string CreateXamlLinkMessage1 {
            get {
                return ResourceManager.GetString("CreateXamlLinkMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can delete or update the link at a later time..
        /// </summary>
        internal static string CreateXamlLinkMessage2 {
            get {
                return ResourceManager.GetString("CreateXamlLinkMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Composers: .
        /// </summary>
        internal static string Credits_Composers {
            get {
                return ResourceManager.GetString("Credits_Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Designers: .
        /// </summary>
        internal static string Credits_Designers {
            get {
                return ResourceManager.GetString("Credits_Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developers: .
        /// </summary>
        internal static string Credits_Developers {
            get {
                return ResourceManager.GetString("Credits_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directors: .
        /// </summary>
        internal static string Credits_Directors {
            get {
                return ResourceManager.GetString("Credits_Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producers: .
        /// </summary>
        internal static string Credits_Producers {
            get {
                return ResourceManager.GetString("Credits_Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speakers: .
        /// </summary>
        internal static string Credits_Speakers {
            get {
                return ResourceManager.GetString("Credits_Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string DeleteFrame {
            get {
                return ResourceManager.GetString("DeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you really want to delete this Frame?.
        /// </summary>
        internal static string DeleteFrameMessage {
            get {
                return ResourceManager.GetString("DeleteFrameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        internal static string ExportCommand {
            get {
                return ResourceManager.GetString("ExportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Cancelled.
        /// </summary>
        internal static string FrameIsNot16By9 {
            get {
                return ResourceManager.GetString("FrameIsNot16By9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Height of the Image should be .
        /// </summary>
        internal static string FrameIsNot16By9Message_Part1 {
            get {
                return ResourceManager.GetString("FrameIsNot16By9Message_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to have the 16:9 Aspect Ratio Required..
        /// </summary>
        internal static string FrameIsNot16By9Message_Part2 {
            get {
                return ResourceManager.GetString("FrameIsNot16By9Message_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Cancelled.
        /// </summary>
        internal static string FrameTooLarge {
            get {
                return ResourceManager.GetString("FrameTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image you are trying to import is too large for a Frame Background.
        /// </summary>
        internal static string FrameTooLargeMessage {
            get {
                return ResourceManager.GetString("FrameTooLargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Cancelled.
        /// </summary>
        internal static string FrameTooSmall {
            get {
                return ResourceManager.GetString("FrameTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image you are trying to import is too small for a Frame Background.
        /// </summary>
        internal static string FrameTooSmallMessage {
            get {
                return ResourceManager.GetString("FrameTooSmallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animation.
        /// </summary>
        internal static string HeaderExpanderForAnimation {
            get {
                return ResourceManager.GetString("HeaderExpanderForAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controls.
        /// </summary>
        internal static string HeaderExpanderForControls {
            get {
                return ResourceManager.GetString("HeaderExpanderForControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string HeaderExpanderForImage {
            get {
                return ResourceManager.GetString("HeaderExpanderForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overlays.
        /// </summary>
        internal static string HeaderExpanderForOverlays {
            get {
                return ResourceManager.GetString("HeaderExpanderForOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soundtrack.
        /// </summary>
        internal static string HeaderExpanderForSoundtrack {
            get {
                return ResourceManager.GetString("HeaderExpanderForSoundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        internal static string HeaderExpanderForVideo {
            get {
                return ResourceManager.GetString("HeaderExpanderForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frames.
        /// </summary>
        internal static string HeaderExpanderFrames {
            get {
                return ResourceManager.GetString("HeaderExpanderFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metadata.
        /// </summary>
        internal static string HeaderExpanderMetadata {
            get {
                return ResourceManager.GetString("HeaderExpanderMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties.
        /// </summary>
        internal static string HeaderExpanderProperties {
            get {
                return ResourceManager.GetString("HeaderExpanderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HelpContents.
        /// </summary>
        internal static string HelpContentsCommand {
            get {
                return ResourceManager.GetString("HelpContentsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        internal static string ImportCommand {
            get {
                return ResourceManager.GetString("ImportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string LoadXaml {
            get {
                return ResourceManager.GetString("LoadXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you load external Xaml you will discard any Image Background you may have added to this Frame..
        /// </summary>
        internal static string LoadXamlMessage1 {
            get {
                return ResourceManager.GetString("LoadXamlMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you still want to proceed?.
        /// </summary>
        internal static string LoadXamlMessage2 {
            get {
                return ResourceManager.GetString("LoadXamlMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author.
        /// </summary>
        internal static string NewDialog_Author {
            get {
                return ResourceManager.GetString("NewDialog_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse.
        /// </summary>
        internal static string NewDialog_Browse {
            get {
                return ResourceManager.GetString("NewDialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string NewDialog_Cancel {
            get {
                return ResourceManager.GetString("NewDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string NewDialog_Location {
            get {
                return ResourceManager.GetString("NewDialog_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string NewDialog_Name {
            get {
                return ResourceManager.GetString("NewDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Project.
        /// </summary>
        internal static string NewDialog_NewProject {
            get {
                return ResourceManager.GetString("NewDialog_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string NewDialog_OK {
            get {
                return ResourceManager.GetString("NewDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string NewDialog_Title {
            get {
                return ResourceManager.GetString("NewDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string NoOSBMain {
            get {
                return ResourceManager.GetString("NoOSBMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no OSBMain Storyboard in this Frame, Animating will not be possible..
        /// </summary>
        internal static string NoOSBMainMessage {
            get {
                return ResourceManager.GetString("NoOSBMainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current project is not Saved, Save Now?.
        /// </summary>
        internal static string NotSavedMessage {
            get {
                return ResourceManager.GetString("NotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string OpenningSameProject {
            get {
                return ResourceManager.GetString("OpenningSameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are attempting to open the current project!  Please close it and reopen it if this is what you intend.
        /// </summary>
        internal static string OpenningSameProjectMessage {
            get {
                return ResourceManager.GetString("OpenningSameProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PageFrame.
        /// </summary>
        internal static string PageFrame {
            get {
                return ResourceManager.GetString("PageFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pageshot.
        /// </summary>
        internal static string PageShot {
            get {
                return ResourceManager.GetString("PageShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string PreviewCommand {
            get {
                return ResourceManager.GetString("PreviewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string ProjectFolderExists {
            get {
                return ResourceManager.GetString("ProjectFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It seems like there is a project in the current location, please select another Project Name.
        /// </summary>
        internal static string ProjectFolderExistsMessage {
            get {
                return ResourceManager.GetString("ProjectFolderExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publish.
        /// </summary>
        internal static string PublishCommand {
            get {
                return ResourceManager.GetString("PublishCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Console Log.
        /// </summary>
        internal static string SaveConsoleCommand {
            get {
                return ResourceManager.GetString("SaveConsoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animation.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Animation {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controls.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Controls {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Image {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overlays.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Overlays {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soundtrack.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Soundtrack {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Soundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        internal static string ScriptPanelDataTemplate_Video {
            get {
                return ResourceManager.GetString("ScriptPanelDataTemplate_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synopsis: .
        /// </summary>
        internal static string ShowProps_Synopsis {
            get {
                return ResourceManager.GetString("ShowProps_Synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags: .
        /// </summary>
        internal static string ShowProps_Tags {
            get {
                return ResourceManager.GetString("ShowProps_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title:  .
        /// </summary>
        internal static string ShowProps_Title {
            get {
                return ResourceManager.GetString("ShowProps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animate.
        /// </summary>
        internal static string TabItemAnimate {
            get {
                return ResourceManager.GetString("TabItemAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Console.
        /// </summary>
        internal static string TabItemConsole {
            get {
                return ResourceManager.GetString("TabItemConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External Links.
        /// </summary>
        internal static string TabItemExternalLinks {
            get {
                return ResourceManager.GetString("TabItemExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string TabItemInfo {
            get {
                return ResourceManager.GetString("TabItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messages.
        /// </summary>
        internal static string TabItemParsingErrors {
            get {
                return ResourceManager.GetString("TabItemParsingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolve Links.
        /// </summary>
        internal static string TabItemResolveLinks {
            get {
                return ResourceManager.GetString("TabItemResolveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resource Links.
        /// </summary>
        internal static string TabItemResourceLinks {
            get {
                return ResourceManager.GetString("TabItemResourceLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Script.
        /// </summary>
        internal static string TabItemScript {
            get {
                return ResourceManager.GetString("TabItemScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        internal static string TabItemShow {
            get {
                return ResourceManager.GetString("TabItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitles.
        /// </summary>
        internal static string TabItemSubtitles {
            get {
                return ResourceManager.GetString("TabItemSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SyncLink.
        /// </summary>
        internal static string TabItemSyncLink {
            get {
                return ResourceManager.GetString("TabItemSyncLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        internal static string TabItemTime {
            get {
                return ResourceManager.GetString("TabItemTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xaml Links.
        /// </summary>
        internal static string TabItemXamlLinks {
            get {
                return ResourceManager.GetString("TabItemXamlLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapse.
        /// </summary>
        internal static string ToolTipCollapse {
            get {
                return ResourceManager.GetString("ToolTipCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string ToolTipControlPanePreviewButton {
            get {
                return ResourceManager.GetString("ToolTipControlPanePreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publish.
        /// </summary>
        internal static string ToolTipControlPanePublishButton {
            get {
                return ResourceManager.GetString("ToolTipControlPanePublishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run Frame Animation.
        /// </summary>
        internal static string ToolTipControlPaneRunFrameAnimationButton {
            get {
                return ResourceManager.GetString("ToolTipControlPaneRunFrameAnimationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand.
        /// </summary>
        internal static string ToolTipExpand {
            get {
                return ResourceManager.GetString("ToolTipExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export toTeleprompt.
        /// </summary>
        internal static string ToolTipExportToTeleprompt {
            get {
                return ResourceManager.GetString("ToolTipExportToTeleprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Frame Animation.
        /// </summary>
        internal static string ToolTipFrameAnimatingIsOff {
            get {
                return ResourceManager.GetString("ToolTipFrameAnimatingIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause Frame Animation.
        /// </summary>
        internal static string ToolTipFrameAnimatingIsOn {
            get {
                return ResourceManager.GetString("ToolTipFrameAnimatingIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Frame Animation.
        /// </summary>
        internal static string ToolTipFrameAnimation {
            get {
                return ResourceManager.GetString("ToolTipFrameAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate to SyncLink.
        /// </summary>
        internal static string ToolTipGoToSyncLink {
            get {
                return ResourceManager.GetString("ToolTipGoToSyncLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Include in Preview.
        /// </summary>
        internal static string ToolTipIncludeInPreview {
            get {
                return ResourceManager.GetString("ToolTipIncludeInPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert/Change Channel Image.
        /// </summary>
        internal static string ToolTipInsertChannelImage {
            get {
                return ResourceManager.GetString("ToolTipInsertChannelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert/Change Channel Logo.
        /// </summary>
        internal static string ToolTipInsertChannelLogo {
            get {
                return ResourceManager.GetString("ToolTipInsertChannelLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Image Background.
        /// </summary>
        internal static string ToolTipInsertImageBackground {
            get {
                return ResourceManager.GetString("ToolTipInsertImageBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert MoreMenu.
        /// </summary>
        internal static string ToolTipInsertMoreMenu {
            get {
                return ResourceManager.GetString("ToolTipInsertMoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert/Change Main Narrative Video.
        /// </summary>
        internal static string ToolTipInsertNVideo {
            get {
                return ResourceManager.GetString("ToolTipInsertNVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Text Animation.
        /// </summary>
        internal static string ToolTipInsertTextAnimation {
            get {
                return ResourceManager.GetString("ToolTipInsertTextAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Tintifier.
        /// </summary>
        internal static string ToolTipInsertTintifier {
            get {
                return ResourceManager.GetString("ToolTipInsertTintifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert WatchClip.
        /// </summary>
        internal static string ToolTipInsertWatchClip {
            get {
                return ResourceManager.GetString("ToolTipInsertWatchClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Xaml from Blend.
        /// </summary>
        internal static string ToolTipInsertXamlFromBlend {
            get {
                return ResourceManager.GetString("ToolTipInsertXamlFromBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Zoom/Pan.
        /// </summary>
        internal static string ToolTipInsertZoomPan {
            get {
                return ResourceManager.GetString("ToolTipInsertZoomPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lock Frame.
        /// </summary>
        internal static string ToolTipLockFrame {
            get {
                return ResourceManager.GetString("ToolTipLockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Volume.
        /// </summary>
        internal static string ToolTipMasterVolume {
            get {
                return ResourceManager.GetString("ToolTipMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Down.
        /// </summary>
        internal static string ToolTipMoveDown {
            get {
                return ResourceManager.GetString("ToolTipMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Up.
        /// </summary>
        internal static string ToolTipMoveUp {
            get {
                return ResourceManager.GetString("ToolTipMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mute Video - Off.
        /// </summary>
        internal static string ToolTipMuteVideoIsOff {
            get {
                return ResourceManager.GetString("ToolTipMuteVideoIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mute Video - On.
        /// </summary>
        internal static string ToolTipMuteVideoIsOn {
            get {
                return ResourceManager.GetString("ToolTipMuteVideoIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Frame.
        /// </summary>
        internal static string ToolTipNewFrame {
            get {
                return ResourceManager.GetString("ToolTipNewFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recording mode is Off.
        /// </summary>
        internal static string ToolTipRecordingModeIsOff {
            get {
                return ResourceManager.GetString("ToolTipRecordingModeIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recording mode is On.
        /// </summary>
        internal static string ToolTipRecordingModeIsOn {
            get {
                return ResourceManager.GetString("ToolTipRecordingModeIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Expand Mode.
        /// </summary>
        internal static string ToolTipToggleExpandMode {
            get {
                return ResourceManager.GetString("ToolTipToggleExpandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VideoFrame.
        /// </summary>
        internal static string ToolTipVideoFrame {
            get {
                return ResourceManager.GetString("ToolTipVideoFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom to Extents.
        /// </summary>
        internal static string ToolTipZoomToExtents {
            get {
                return ResourceManager.GetString("ToolTipZoomToExtents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VideoFrame.
        /// </summary>
        internal static string VideoFrame {
            get {
                return ResourceManager.GetString("VideoFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Webslide.
        /// </summary>
        internal static string WebSlide {
            get {
                return ResourceManager.GetString("WebSlide", resourceCulture);
            }
        }
    }
}
